/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.yakindu.analysis.example;

import hu.bme.mit.yakindu.analysis.IStatemachine;
import hu.bme.mit.yakindu.analysis.ITimerCallback;

public interface IExampleStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseGo();
		
		public void raiseRed();
		
		public void raiseGreen();
		
		public long getRedTime();
		
		public void setRedTime(long value);
		
		public long getGreenTime();
		
		public void setGreenTime(long value);
		
	}
	
	public SCInterface getSCInterface();
	
}
